package br.com.roboparts.entity;

public enum AuditAction {
 USER_REGISTERED, USER_LOGGED_IN, USER_LOGGED_OUT,
 ROBOT_CREATED, ROBOT_UPDATED, NODE_CREATED, NODE_UPDATED,
 CHECKLIST_STARTED, COMPONENT_WITHDRAWN, COMPONENT_RETURNED, CHECKLIST_FINALIZED, CHECKLIST_CANCELLED
}
